# Generated by Django 4.2.11 on 2024-04-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_alter_user_avatar"),
        ("business", "0002_paper_score_count"),
    ]

    operations = []
