# Generated by Django 4.2.11 on 2024-04-15 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_merge_0002_alter_user_avatar_0002_paper_score_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchRecord",
            fields=[
                (
                    "search_record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("conversation_path", models.CharField(max_length=255, unique=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
            ],
        ),
    ]
