# Generated by Django 4.2.11 on 2024-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_searchrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filereading",
            name="conversation_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="searchrecord",
            name="conversation_path",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
