# Generated by Django 4.2.11 on 2024-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_alter_searchrecord_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryreport",
            name="title",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
