# Generated by Django 4.2.11 on 2024-04-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_summaryreport_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdocument",
            old_name="upload_time",
            new_name="upload_date",
        ),
    ]
