# Generated by Django 4.2.11 on 2024-04-19 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_summaryreport_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "admin_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("admin_name", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
