# Generated by Django 4.2.11 on 2024-04-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentreport",
            name="comment_id",
        ),
        migrations.AddField(
            model_name="commentreport",
            name="comment_id_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.firstlevelcomment",
            ),
        ),
        migrations.AddField(
            model_name="commentreport",
            name="comment_id_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.secondlevelcomment",
            ),
        ),
        migrations.AddField(
            model_name="commentreport",
            name="comment_level",
            field=models.IntegerField(default=1),
        ),
    ]
