# Generated by Django 4.2.11 on 2024-04-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0009_remove_commentreport_comment_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secondlevelcomment",
            old_name="lever1_comment",
            new_name="level1_comment",
        ),
    ]
