# Generated by Django 4.2.11 on 2024-04-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_rename_upload_time_userdocument_upload_date"),
        ("business", "0010_rename_lever1_comment_secondlevelcomment_level1_comment"),
    ]

    operations = []
