# Generated by Django 4.2.11 on 2024-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0011_merge_20240422_1931"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummaryReport",
        ),
    ]
