# Generated by Django 4.2.11 on 2024-04-22 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_delete_summaryreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("report_path", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
            ],
        ),
    ]
