# Generated by Django 4.2.11 on 2024-04-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_alter_filereading_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileReading",
        ),
    ]
