# Generated by Django 4.2.11 on 2024-04-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0015_delete_filereading"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("conversation_path", models.CharField(max_length=255, null=True)),
                (
                    "document_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.userdocument",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paper",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "conversation_path")},
            },
        ),
    ]
