# Generated by Django 4.2.11 on 2024-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0016_filereading"),
    ]

    operations = [
        migrations.AddField(
            model_name="filereading",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
