# Generated by Django 4.2.11 on 2024-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0017_filereading_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
