# Generated by Django 4.2.11 on 2024-04-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0018_userdocument_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="summary",
        ),
    ]
