# Generated by Django 4.2.11 on 2024-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0021_searchrecord_related_papers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreport",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentreport",
            name="judgment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
