# Generated by Django 4.2.11 on 2024-05-16 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0022_alter_commentreport_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "subclass_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="paper",
            name="sub_classes",
            field=models.ManyToManyField(related_name="papers", to="business.subclass"),
        ),
    ]
