# Generated by Django 4.2.11 on 2024-05-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0023_userdailystatistic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdailystatistic",
            name="total",
        ),
    ]
