# Generated by Django 4.2.11 on 2024-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_userdailyaddition_delete_userdailystatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='status',
            field=models.CharField(choices=[('P', '未生成'), ('IP', '生成中'), ('C', '已生成')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='userdailyaddition',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
