# Generated by Django 4.2.11 on 2024-05-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0023_subclass_paper_sub_classes"),
        ("business", "0026_summaryreport_status_alter_userdailyaddition_date"),
    ]

    operations = []
