# Generated by Django 4.2.11 on 2024-05-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0027_merge_20240517_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstlevelcomment",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="secondlevelcomment",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
