# Generated by Django 4.2.11 on 2024-05-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0028_firstlevelcomment_visibility_and_more"),
        ("business", "0029_alter_abstractreport_status"),
    ]

    operations = []
