# Generated by Django 4.2.11 on 2024-05-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_alter_abstractreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractreport',
            name='status',
        ),
    ]
