# Generated by Django 4.2.11 on 2024-05-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0030_merge_20240523_2107"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreport",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
