# Generated by Django 4.2.11 on 2024-05-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_remove_abstractreport_status'),
        ('business', '0031_commentreport_processed'),
    ]

    operations = [
    ]
