# Generated by Django 4.2.11 on 2024-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0035_alter_abstractreport_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("ip_address", "timestamp")},
            },
        ),
    ]
